### ISSUE TITLE
Finger Abduction Tutorial - Denoising Error

### ISSUE THREAD

**Issue by georgeoneill** [neurofractal/analyse_OPMEG#17]
**EDIT:** I think I have misunderstood the code - nevermind. But I'll keep the question below _just incase_ I was right the first time? I need more tea. - Sorry!

> Hey hey,
> 
> Nice job on the tutorial - I wasn't aware you could have a MATLAB Jupyter notebook. 
> 
> I just wanted to ask about the synthetic gradiometry. Is there any reason why you have omitted the radial sensors from the reference array? If you are using TAN only you are (in the case of how the array is set up in the FIL prior to the current shutdown) restricitng to only interference in one direction (floor-to-ceiling axis). Therefore you are losing two of the directional components of the interence (which the RAD channels on the sensors are seeing). 
> 
> G

**Comment by neurofractal** [comment]
Hi George, 

:) Yeah for the tutorial, I used TAN+RAD references together, but only for TAN OPMEG sensors

On another point, I have noticed that the synthetic gradiometry sometimes spreads noise across the frequency spectrum, rather than reducing it. Perhaps we could look at this together next week?

**Comment by neurofractal** [comment]
Would also be very interesting to test (when back in the lab) whether adding more references around the room is able to help regress out even more noise...

**Comment by georgeoneill** [comment]
> :) Yeah for the tutorial, I used TAN+RAD references together, but only for TAN OPMEG sensors
Excellent, thats good.

> On another point, I have noticed that the synthetic gradiometry sometimes spreads noise across the frequency spectrum, rather than reducing it. Perhaps we could look at this together next week?

Yes this is an effect I have seen a few times too. We should open a new issue about that?

It shouln't do this _unless_ we are doing some kind of additve process (maybe trying to double regress the same signal???). I feel like Tim may have already have some intuition as to across why this happens but this should be something we can get a handle on when I look a bit more at the code.
