### ISSUE TITLE
Synthetic Gradiometry spreads out noise (sometimes)

### ISSUE THREAD

**Issue by neurofractal** [neurofractal/analyse_OPMEG#18]
> On another point, I have noticed that the synthetic gradiometry sometimes spreads noise across the frequency spectrum, rather than reducing it. Perhaps we could look at this together next week?

Yes this is an effect I have seen a few times too. We should open a new issue about that?

It shouln't do this _unless_ we are doing some kind of additve process (maybe trying to double regress the same signal???). I feel like Tim may have already have some intuition as to across why this happens but this should be something we can get a handle on when I look a bit more at the code.

_Originally posted by @georgeoneill in https://github.com/neurofractal/analyse_OPMEG/issues/17#issuecomment-605070102_

**Comment by neurofractal** [comment]
> It shouln't do this _unless_ we are doing some kind of additve process (maybe trying to double regress the same signal???).

Perhaps this occurs when adding multiple reference regressors for specific frequency bands?

**Comment by georgeoneill** [comment]
Do you have a dataset/input parameters where this causes it to happen? It should give me somewhere to start with this tomorrow.

**Comment by neurofractal** [comment]
I sure do. Will let you know :)

**Comment by neurofractal** [comment]
Hi @georgeoneill 

Have had a quick look at this today. The 'spreading out noise' phenomenon seems to happen in two situations:

**1) There is no filtering of data at all**
![image](https://user-images.githubusercontent.com/18535653/78051702-fbbc2200-7375-11ea-9ba9-7f4d71e10320.png)

**2) Filtering to remove high-frequency peaks (e.g. around 80Hz).**
e.g. using cfg.filter_ref = [1 20; 40 60; 80 90];
![image](https://user-images.githubusercontent.com/18535653/78051896-3cb43680-7376-11ea-84d1-f04c2465bfa6.png)

Script looks something like this (data [here](https://liveuclac-my.sharepoint.com/:f:/g/personal/skgtsey_ucl_ac_uk/ErP0UX3sbRVCmnKrttLDtNIB5p1WxS_8kGWUCIo_A75lwA?e=mqGy0s))

```matlab
%% Paths (RS)
fieldtripDir    = '/Users/rseymoue/Documents/scripts/fieldtrip-20191213';
script_dir      = '/Users/rseymoue/Documents/GitHub/analyse_OPMEG';
data_dir        = '/Volumes/Robert T5/OPM_data/benchmarking_26_02/';
save_dir        = '/Users/rseymoue/Documents/GitHub/opm_benchmarking_feb_2020/';

% Add Fieldtrip to path
disp('Adding Fieldtrip and analyse_OPMEG to your MATLAB path');
addpath(fieldtripDir)
ft_defaults;

% Add analyse_OPMEG Scripts to path
addpath(genpath(script_dir));

% cd to save dir
cd(save_dir)

%% (2) Start preprocessing.
% Read in the raw data using BIDS
cfg             = [];
cfg.folder      = data_dir;
cfg.precision   = 'single';
cfg.bids.task   = 'faces';
cfg.bids.sub    = '002';
cfg.bids.ses    = '001';
cfg.bids.run    = '001';
rawData         = ft_opm_create(cfg);

%% Highp-pass filter at 2Hz and low-pass filter at 100Hz to remove large peaks
cfg = [];
cfg.hpfilter    = 'yes';
cfg.hpfreq      = 2;
cfg.hpfiltord   = 5;
rawData         = ft_preprocessing(cfg,rawData);

cfg = [];
cfg.lpfilter    = 'yes';
cfg.lpfreq      = 100;
cfg.lpfiltord   = 5;
rawData         = ft_preprocessing(cfg,rawData);


%% Plot PSD
cfg                 = [];
cfg.channel         = vertcat(ft_channelselection_opm('MEG',rawData),...
     '-N0-TAN','-N4-TAN','-N3-TAN','-MV-TAN');
cfg.trial_length    = 3;
cfg.method          = 'tim';
cfg.foi             = [1 100];
cfg.plot            = 'yes';
pow                 = ft_opm_psd(cfg,rawData);
ylim([1 1e4])

%% Plot PSD of References
cfg                 = [];
cfg.channel         = vertcat(ft_channelselection_opm('MEGREF',rawData));
cfg.trial_length    = 3;
cfg.method          = 'tim';
cfg.foi             = [1 100];
cfg.plot            = 'yes';
pow                 = ft_opm_psd(cfg,rawData);
ylim([1 1e4])

%% Perform synthetic gradiometry on TAN sensors
cfg = [];
cfg.channel = vertcat(ft_channelselection_opm('MEG',rawData),...
     '-N0-TAN','-N4-TAN','-N3-TAN','-MV-TAN','-N0-RAD','-N4-RAD',...
     '-N3-RAD','-MV-RAD');
cfg.refchannel = 'MEGREF';
cfg.filter_ref = [1 20; 40 60];
cfg.derivative = 'yes';
cfg.return_all = 'no';
[rawData2] = ft_opm_synth_gradiometer(cfg,rawData);


% cfg                 = [];
% cfg.channel         = vertcat(ft_channelselection_opm('MEG',rawData),...
%      '-N0-TAN','-N4-TAN','-N3-TAN','-MV-TAN','-N0-RAD','-N4-RAD',...
%      '-N3-RAD','-MV-RAD');
% cfg.trial_length    = 3;
% cfg.method          = 'tim';
% cfg.foi             = [1 100];
% cfg.plot            = 'yes';
% cfg.dB              = 'yes';
% pow                 = ft_opm_psd_compare(cfg,rawData,rawData2);

% Plot PSD of 'cleaned' data
cfg                 = [];
cfg.channel         = vertcat(ft_channelselection_opm('MEG',rawData),...
     '-N0-TAN','-N4-TAN','-N3-TAN','-MV-TAN','-N0-RAD','-N4-RAD',...
     '-N3-RAD','-MV-RAD');
cfg.trial_length    = 3;
cfg.method          = 'tim';
cfg.foi             = [1 100];
cfg.plot            = 'yes';
pow                 = ft_opm_psd(cfg,rawData2);
ylim([1 1e4])
```

**Comment by georgeoneill** [comment]
Thanks @neurofractal I’ll take a look at this tomorrow and see if I can get to the bottom of this.

**Comment by georgeoneill** [comment]
Following up on the telecon earlier, I've had a look at whether the Optitrak data is leaking through before I try and fix the gradiometry, just incase that this may still be leaking through. In blue is a random selected scalp sensor filtered between 80-90 Hz using the FieldTrip defaults. and in orange is the sync trigger for the Optitrak.

![image](https://user-images.githubusercontent.com/3579812/78270370-a5c8b500-7502-11ea-806d-e743d4e515d2.png)

So we need to have a think about how to best filter to minimise this, if this isn't general infra-red chaos upsetting the apple cart.

**Comment by neurofractal** [comment]
Makes sense... I suspect you can even see this on every channel, when the opti-track is turned on around 40s

Does the same happen for the 37ish Hz peak?

**Comment by georgeoneill** [comment]
>
> Makes sense... I suspect you can even see this on every channel, when the opti-track is turned on around 40s
>

Yup, here is the change in variance in 35 second a window before and 35 seconds during the optitrak being on.
![image](https://user-images.githubusercontent.com/3579812/78277211-0ad4d880-750c-11ea-8660-4ba3fd5d3387.png)

>
> Does the same happen for the 37ish Hz peak?
>

Not that I would confidently claim, if there is an effect its orders of magnitude lower. (filtered between 30-45 Hz).

![image](https://user-images.githubusercontent.com/3579812/78277442-6f903300-750c-11ea-828e-78c8f7d4d90f.png)

**Comment by georgeoneill** [comment]
Also, as a test to see whether doing this trial by trial improved matters. Sadly not. If anything the performance gets worse, even in the lower test bands.

![trial](https://user-images.githubusercontent.com/3579812/78279279-33120680-750f-11ea-9796-96f7f8bdcf25.png)

**Comment by neurofractal** [comment]
> Also, as a test to see whether doing this trial by trial improved matters. Sadly not. If anything the performance gets worse, even in the lower test bands.
> 
> ![trial](https://user-images.githubusercontent.com/3579812/78279279-33120680-750f-11ea-9796-96f7f8bdcf25.png)

Wow wavy!

**Comment by neurofractal** [comment]
@georgeoneill @tierneytim Done some digging. Band-stop filtering the hell out of the data (this is finger abduction) seems to work:

**Original PSD:**

![image](https://user-images.githubusercontent.com/18535653/78352403-2b4e7280-75a0-11ea-911b-e596b3e30ca2.png)

**After Synth Gradiometry:**

![image](https://user-images.githubusercontent.com/18535653/78352424-343f4400-75a0-11ea-95ec-418e7c414d7b.png)

![image](https://user-images.githubusercontent.com/18535653/78352434-37d2cb00-75a0-11ea-9bf9-6229ec31dc00.png)

**Shielding Factor:**

![image](https://user-images.githubusercontent.com/18535653/78352454-3e614280-75a0-11ea-819b-dd47462bf923.png)

**Comment by georgeoneill** [comment]
@neurofractal That is excellent to see, great job.

**Comment by georgeoneill** [comment]
Just to confirm that filtering out the Optitrak peak is really important. Here is a repeat of channel MY-RAD in the face/scrambled data after the bandstop at 115-125 Hz and prior to any gradiometry.

![image](https://user-images.githubusercontent.com/3579812/78359036-242d6180-75ac-11ea-9513-0c330530b55d.png)

I think we can say that this is the problem solved. Obviously it would be ideal if the regression didn't do this but maybe we should highlight this phenonemnon this as a warning that if the noise gets worse you have an aliased artefact which upsetting everything.?

**Comment by neurofractal** [comment]
We (I) could do some FAQs with this as an issue?

**Comment by neurofractal** [comment]
OK closing this now - think we've worked out not to include huge spectral peaks when doing synthetic gradiometry
