### ISSUE TITLE
Implement DSSP in SPM

### ISSUE THREAD

**Issue by neurofractal** [neurofractal/analyse_OPMEG#27]
Along the lines of: https://github.com/neurofractal/analyse_OPMEG/blob/master/preprocessing/ft_dssp_window.m

Will need some pointers from @georgeoneill

**Comment by georgeoneill** [comment]
*points*

**Comment by georgeoneill** [comment]
Quick question, is `ft_dssp_window` baked into fieldtrip already? Or is this a wrapper you have put together yourself?

**Comment by georgeoneill** [comment]
Okay, some good news is that `ft_denoise_dssp` and by extention the `dssp` subfunction(s) are already in the trunk verion of SPM, meaning we can probably as an intial stopgap take an approach similar to `spm_eeg_ctf_synth_gradiometer` which is just a wrapper for `ft_denoise_syntehtic`. This might make things a lot simpler. Unsure about the windowing method mind, but its something we can talk about.

**Comment by neurofractal** [comment]
Hi George.. so ft_denoise_dssp uses this slightly modified **[dssp.m script](https://github.com/neurofractal/analyse_OPMEG/blob/master/preprocessing/dssp.m)**, where I have taken out some of the superflous code which prints stuff to the command window.

The windowing approach is really simple and includes triangular weighting... we might need modified this for the way SPM reads data from disk?
