### ISSUE TITLE
DSSP in SPM

### ISSUE THREAD

**Issue by tierneytim** [neurofractal/analyse_OPMEG#30]
Hi Guys, 

Would be good to see relative contributions of the projection on the leadffields step vs canonical correlations step. My worry is that  the CCA step is not as stable at low sensor numbers (we've already seen this with it wiping out large amplitude signals). If possible could a flag be added to output the first step alone?

**Comment by neurofractal** [comment]
Yes good point. I guess this is what was happening with some of the earlier data when we only had 12-or-so channels

**Comment by georgeoneill** [comment]
Hi Tim can you have a look at the deltas and see if this is what you were proposing?

**Comment by tierneytim** [comment]
Yes, that should do the trick. Of course, it is rank deficient so it might do some spicy things to the beamformers but it would be good to untangle the contributions.
