### ISSUE TITLE
Issue with chanselection after spm2fieldtrp

### ISSUE THREAD

**Issue by georgeoneill** [neurofractal/analyse_OPMEG#39]
when exporting a MEEG object from SPM to a dat structure in Fieldtrip, ft_channelselection_opm falls over.

**Comment by neurofractal** [comment]
Hi George, think you can get round the issue by using:

```matlab
ftraw = D.ftraw;
ft_channelselection({'all','-XXX'},ftraw.label)
```

Would you be able to share the data with me? Can't seem to get .hdr field to materialise in the tutorial data
