### ISSUE TITLE
Compatibility with new acquisition system ft_opm_psd

### ISSUE THREAD

**Issue by meaghanspedden** [neurofractal/analyse_OPMEG#45]
The sampling frequency is not an integer for the new OPM acq system so nsamps line 211 is not an integer which creates problems for preallocating in line 220. I guess the best solution is just to add floor to line 211?

**Comment by neurofractal** [comment]
It's not an integer - what is it?!

**Comment by meaghanspedden** [comment]
It is 374.9998 :)

Den ons. 4. okt. 2023 kl. 13.10 skrev Robert Seymour <
***@***.***>:

**Comment by neurofractal** [comment]
Of course it 😃 !!! Yeah floor sounds sensible. Do you want to submit a pull request or should I just do it?

**Comment by meaghanspedden** [comment]
Go ahead and do it if you are looking at it now :) thanks

Den ons. 4. okt. 2023 kl. 13.18 skrev Robert Seymour <
***@***.***>:

**Comment by neurofractal** [comment]
https://github.com/neurofractal/analyse_OPMEG/commit/166b81613d6d57bc8f5b51dbd317d811d4393b51

Let me know if it works...

**Comment by meaghanspedden** [comment]
will take a look now thanks

Den ons. 4. okt. 2023 kl. 13.26 skrev Robert Seymour <
***@***.***>:

**Comment by meaghanspedden** [comment]
Yep works great

Den ons. 4. okt. 2023 kl. 13.26 skrev Robert Seymour <
***@***.***>:
